# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: respose.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='respose.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\rrespose.proto\"\xb7\x01\n\x07Respose\x12\x1f\n\x06status\x18\x01 \x02(\x0e\x32\x0f.Respose.Status\x12\x12\n\nserverInfo\x18\x02 \x02(\t\x12\x11\n\tsignature\x18\x03 \x02(\x0c\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\x0c\x12\x17\n\x0fprotocolVersion\x18\x05 \x01(\t\x12\x0b\n\x03url\x18\x06 \x01(\t\x12\x10\n\x08\x65ncoding\x18\x07 \x01(\t\"\x1b\n\x06Status\x12\x06\n\x02OK\x10\x01\x12\t\n\x05\x45RROR\x10\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_RESPOSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='Respose.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=174,
  serialized_end=201,
)
_sym_db.RegisterEnumDescriptor(_RESPOSE_STATUS)


_RESPOSE = _descriptor.Descriptor(
  name='Respose',
  full_name='Respose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='Respose.status', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serverInfo', full_name='Respose.serverInfo', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signature', full_name='Respose.signature', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='Respose.content', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='protocolVersion', full_name='Respose.protocolVersion', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='url', full_name='Respose.url', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='encoding', full_name='Respose.encoding', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RESPOSE_STATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=201,
)

_RESPOSE.fields_by_name['status'].enum_type = _RESPOSE_STATUS
_RESPOSE_STATUS.containing_type = _RESPOSE
DESCRIPTOR.message_types_by_name['Respose'] = _RESPOSE

Respose = _reflection.GeneratedProtocolMessageType('Respose', (_message.Message,), dict(
  DESCRIPTOR = _RESPOSE,
  __module__ = 'respose_pb2'
  # @@protoc_insertion_point(class_scope:Respose)
  ))
_sym_db.RegisterMessage(Respose)


# @@protoc_insertion_point(module_scope)
